### ISSUE TITLE
Investment - Kicktstarter - Rewards

### ISSUE THREAD

**Issue by stefek99** [astralship/astralship.github.io#16]
- [x] £300 for the whole day? (bargain)
- [x] 1.5x multiplier (too much)

@quantumLeaf please review the points above.

**Comment by quantumLeaf** [comment]
I agree it's cheap. But then we would like to get booking and still 100k for the whole year. 
£350? If we push to £400 then I think facilitation is cheap at £100 but then again it is our labour so maybe we can do £400. Your call. 

1.5x yes, maybe its too much. But we can allows change it if we get too much take up. I think its pretty unlikely get much. How about 1.3x?

**Comment by stefek99** [comment]
I was thinking about 1.2x multiplier. iPhones keep their value. Same principle applies to us - do not devaluate. 20% bonus kickback multiplier is already generous.

To rent the whole space... And what about the crew? 10 / 15 / 20 people are now without a home? The way I see it - existing, unaffected offices, crew cabins and only the large open common space that is available for hire... I don't want some random event to disrupt my work.

I was thinking that rather than days we could hire space in 6 hours chunks - 6 hours of solid work is already a lot. Also allows us to hire space twice a day! 8-14 and 15-21...

*(I know that this bit of website wasn't fully polished but we wouldn't have this discussion if it wasn't there already)*

**Comment by quantumLeaf** [comment]
Potentially there is a big gap in alignment here. We need to check. 

I don't see the Astralship as being a home for anyone. Either people are on a voyage (for say 2 weeks) living and working on ship, or they are somewhere else. In our case this could be in the vestry. Other sailors will need to have their own home. As facilitators would could be part time on the voyage too. 

We might sail many times a year and spend a lot of time on the voyage, but for me an essential of the ship concept is that everyone onboard is focussed on achieving the same goal. If we take this out we have a home with some co-working space. That not to say there couldn't be times with the business plan when the ship isnt on voyage and we have independent working, but this isnt voyaging. 

For me the point is we have an optional revenue stream of hiring out the ship. We dont HAVE to rent it out if we don't want the money. If we can afford it and want to sail all the time then that fine. However, Michal working on Michals projects while other people are on voyage isn't going to work. It breaks the focus of Astralship. Michal leading a voyage on his own project is entirely feasible but this must have a well defined start and end and be financially viable.

**Comment by stefek99** [comment]
I was intending to live on a ship.

And participate in projects.

My personal stuff - I can visit other places.

Vestry as housing unit (including my kids) super cool.

All falling into place, quantum alignment...

I was just worried that we are on the voyage and then out of the sudden someone rents the astralship and kicks us out 😇

**Comment by quantumLeaf** [comment]
Ok! Good news. Just had to check.
Were in control. We can make a small number of weeks available at a lower
price, then increase. Who knows,  may find we take in a lot of funding that
was if we people really buy in to it and don't want to miss out. Might mean
the first year we will have to voyage less but we will have achieved a lot.
If rather do 4 amazing voyages a year than a mediocre one each month.

**Comment by stefek99** [comment]
1 week of voyaging = 1 week time off :) 

(at least)

**Comment by quantumLeaf** [comment]
Maybe that should be a pirate law minimum. Aid peak performance. We can do
some science on it later
