### ISSUE TITLE
Create JOBS pages with some listings, notably: ONLINE MARKETING + SOCIAL MEDIA

### ISSUE THREAD

**Issue by stefek99** [astralship/astralship.github.io#22]
We are getting ready for Kickstarter campaign.

We will be reaching out to a vast amount of people.

We need to find someone who is good at online marketing, marketing automation, content, inbound leads, growth hacking... I have no idea what are state of the art tools in 2017 and I'm usually controversial / quirky / eccentric so my content might not be that good...

Related: http://blog.capterra.com/hubspot-competitors-marketing-automation/

**Comment by quantumLeaf** [comment]
I can try to find someone in India if we have a lot of this kind of work

**Comment by stefek99** [comment]
Exactly / great / approved.

It makes sense to hire someone who charges "single digit" dollars per hour :)

On the other hand it would be nice to have someone on board...

**Comment by quantumLeaf** [comment]
yes, I have some good people in mind. 1 in particular. We can start there. When are you thinking this should start?

**Comment by stefek99** [comment]
ASAP!

Related Trello card: https://trello.com/c/RDY8rdwz/14-social-media-strategy

**Comment by stefek99** [comment]
We need to have JOBS page... See also: https://trello.com/c/OpKFSwhE/12-register-a-trademark-so-that-we-can-use-astralship

**Comment by stefek99** [comment]
astralship.org/jobs.html

**Comment by stefek99** [comment]
New jobs titles:

- maker in residence
- hacker in residence
- activisit in residence
- entrepreneur in residence

Explain how it related to `jobs` `services` and `stay`

**Comment by stefek99** [comment]
Ambassadors!

(we need more people)
