### ISSUE TITLE
Enhance the images on the homepage

### ISSUE THREAD

**Issue by stefek99** [astralship/astralship.github.io#23]
Some recent photos - https://drive.google.com/drive/folders/0Bx1otHS4yU_2ckp4UFZ1U3JKcGc - I like the sheep and nature and sunset.

Currently:
- [ ] THE VOYAGES and STUNNING NATURAL LOCATION very similar
- [ ] TOTAL IMMERSION messy
- [ ] WHAT IS ASTRALSHIP? messy

**Comment by stefek99** [comment]
About point 1 - these two images are too similar.

![image](https://cloud.githubusercontent.com/assets/249703/23230006/407e990e-f93a-11e6-8c4f-12c7eed90680.png)

**Comment by stefek99** [comment]
I don't get this image...

We can do much better.

I have no idea what it shows :/

@quantumLeaf 

![image](https://cloud.githubusercontent.com/assets/249703/23282714/6ab9a912-fa1a-11e6-87d1-510149686c43.png)

**Comment by quantumLeaf** [comment]
That was the point. The title is 'what is astralship?'  the picture is
supposed to make you think 'hmm, what is this? Looks interesting'

**Comment by stefek99** [comment]
It's messy.
It doesn't show anything specific.
It triggers more questions.
Not cool.
People have enough worries / troubles / questions.
We should provide solutions, rather than expecting them to...

**Comment by stefek99** [comment]
Related to #18 

Replace one repetitive image with CAD model.

@quantumLeaf possible?

**Comment by quantumLeaf** [comment]
If it's the same image we were discussing, the feedback I'm getting is
positive and that image. However you mention repetition so I'm not sure if
we mean the same one. I think cad is not ready. No need to tweak images on
the website at the moment. We can discuss tomorrow.

**Comment by stefek99** [comment]
Of course CAD model is not ready but even the current state "work in progress" is better than duplicate images...

![image](https://cloud.githubusercontent.com/assets/249703/23586995/c88f3cec-0199-11e7-902f-4e6874e650af.png)

**Comment by stefek99** [comment]
Use some of these: https://drive.google.com/drive/folders/0Bx1otHS4yU_2ckp4UFZ1U3JKcGc

Or make new one.

I don't like mess, I don't like stickies... The other day I've heard argument "makes people think" - I don't want to think, I want to see clear vision.

Current CAD model is way better than duplicate, chaotic images.

![image](https://cloud.githubusercontent.com/assets/249703/23587006/1e693eb0-019a-11e7-9997-b096225d2b5f.png)

**Comment by stefek99** [comment]
#3 #32 #18 

OMG! We have 4 issues related to images...

I'm not big fan of the existing selection...

I'd like to use:
* CAD model (even the current state)
* Blockchain Earth (we are connected, we appeal to visionary thinkers)
* Borrow an image from the game (because it is cool)

If we really want to show the chapel we have dedicated gallery page: http://astralship.org/gallery

Home page should be inspirational and aspirational. Fake it till you make it... (we can present forward looking statements, we are not publicly traded company that needs to isses diclaimers all the time)

**Comment by stefek99** [comment]
We should also consider using Neural Networks images by Rishabh...

HDR interior of the chapel must go first!

**Comment by stefek99** [comment]
Closing #3 as duplicate. We definitely should reuse one of these: [image search for astral ship](https://www.google.co.uk/search?site=&tbm=isch&source=hp&biw=1856&bih=1080&q=astralship&oq=astralship&gs_l=img.3..0i10i24k1j0i24k1.1083.4858.0.5506.15.13.2.0.0.0.134.1208.4j7.11.0.ulpcf,cfro%3D1,stargd-cl%3Dweb-for-rerank-with-language,eulp%3D1,erulps%3D1...0...1.1.64.img..2.12.1114.0..0j35i39k1j0i30k1j0i5i30k1.xjNjjULhl9A&gws_rd=cr&ei=s5n4WPaFBsyiwAKzzKKACQ#q=astral+ship&tbm=isch&tbas=0)

Closing #32 as duplicate.

http://i.huffpost.com/gen/4332566/images/o-CONNECTED-PLANET-facebook.jpg
http://www.huffingtonpost.com/david-seaman/ethereum-tests-light-spee_b_11452612.html

Closing #18 as duplicate.

Let's grab CAD model and embed on the website: https://www.babylonjs.com/

---

And then think about priorities... No image can help if there is no traffic... We should use a number of automated tools.
