### ISSUE TITLE
Remove address from the website to aid with privacy and security

### ISSUE THREAD

**Issue by stefek99** [astralship/astralship.github.io#25]
@quantumLeaf would probably agree.

We are rather public and if someone does a lot of digging will find it anyway.

We can at least make it in a way - easier to join Slack and become friends - that behave like a thug :)

**Comment by quantumLeaf** [comment]
Yes. Is this coming from somewhere? I feel we should be too public yet.

**Comment by stefek99** [comment]
Phone conversation with a friend.

He asked me about the location of the chapel.

I mentioned we have contact + FAQ... And after brief discussion we reached conclusion that `contact first` is the right approach, auto invite to Slack will help...
