### ISSUE TITLE
Change CNC manufacturing as it is non obvious to the general public

### ISSUE THREAD

**Issue by stefek99** [astralship/astralship.github.io#4]
Introduce process for resolving immediate changes to the website.

**Comment by stefek99** [comment]
For the record - https://trends.google.co.uk/trends/explore?q=CNC%20manufacturing,3d%20printing - **3D printing** is much widely understood...

![image](https://cloud.githubusercontent.com/assets/249703/23097210/02f07362-f626-11e6-8db0-402a28aebbf4.png)

**Comment by quantumLeaf** [comment]
![screen shot 2017-02-18 at 22 06 11](https://cloud.githubusercontent.com/assets/579254/23097235/a10416b2-f626-11e6-9710-7106d5773755.png)

**Comment by stefek99** [comment]
We should prioritise user feedback. Especially if one of us (me) agrees with it. We could have a range of things, ranging from ... and ... to ... and ...

*(anything crazy will fit without changing overall sense)

**Comment by stefek99** [comment]
Thanks for using `advanced` language!
