### ISSUE TITLE
Add Liam to formspree

### ISSUE THREAD

**Issue by quantumLeaf** [astralship/astralship.github.io#42]
2 recipients is possible

**Comment by stefek99** [comment]
Currently the form doesn't receive much traffic anyway.

Maybe to create email in astralship.org domain? 

https://trello.com/c/1DtCH4lP/11-connect-email-with-astralship-org-googleapps-5-user-month

**Comment by quantumLeaf** [comment]
happy with signing up. i think this is an easier done than said issue for you though

**Comment by stefek99** [comment]
![image](https://cloud.githubusercontent.com/assets/249703/23835983/f35945f8-0770-11e7-81fc-771786326c6a.png)


Of course it done, sir.
