### ISSUE TITLE
Feature fucking image and start making out of it from fucking licenses

### ISSUE THREAD

**Issue by stefek99** [astralship/astralship.github.io#88]
https://steemit.com/art/@elohprojects/astralship-future-legends-flagship-image-release-a-beat-by-beat-explanation

Already sold the thing for `0.4 BTC` to Don Pepe Louis.

*(there is a magical potential here babes)*

![image](https://user-images.githubusercontent.com/249703/41186391-9b06a102-6b8d-11e8-8430-9831757a2f96.png)

https://www.instagram.com/p/BeKMfy2A4uT/?taken-by=astralship

**Comment by quantumLeaf** [comment]
not sure what is meant by this.
